apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery
  labels:
    app: delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery
  template:
    metadata:
      name: delivery
      labels:
        app: delivery
    spec:
      containers:
        - name: delivery-webserver
          image: fagnervalente/postech-soat-webserver
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /usr/app
              name: api
          volumes:
            - name: api
              persistentVolumeClaim:
                claimName: webserver-claim0
          resources:
            requests:
              cpu: 1m
            limits:
              cpu: 1m
              memory: 128Mi
  