apiVersion: v1
kind: Pod
metadata:
  name: api-delivery
  labels:
    app: api-delivery
spec:
  containers:
    - name: api-delivery-container
      image: fagnervalente/postech-soat-webserver
      ports:
        - containerPort: 3000
      envFrom:
        - configMapRef:
            name: delivery-configmap