apiVersion: v1
kind: Pod
metadata:
  name: db-delivery
  labels:
    app: db-delivery
spec:
  containers:
    - name: db-delivery-container
      image: postgres:14-alpine
      ports:
        - containerPort: 5432
      envFrom:
        - configMapRef:
            name: delivery-configmap
      env:
        - name: POSTGRES_DB
          value: $(DATABASE_NAME)
        - name: POSTGRES_USER
          value: $(DATABASE_USER)
        - name: POSTGRES_PASSWORD
          value: $(DATABASE_PASSWORD)
      livenessProbe:
        exec:
          command:
            - pg_isready
        failureThreshold: 5
        periodSeconds: 10
        timeoutSeconds: 5
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresdb
      resources:
        requests:
          cpu: 1m
          memory: 128Mi
        limits:
          cpu: 1m
          memory: 128Mi
  volumes:
    - name: postgresdb
      persistentVolumeClaim:
        claimName: delivery-db-pvc